service: cowinator-socket
frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: 'dev'
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:Query"
            - "dynamodb:Get*"
            - "dynamodb:PutItem"
            - "dynamodb:Delete*"
            - "dynamodb:Update*"
          Resource:
            - !GetAtt cowinatorTable.Arn
            - !Join
              - '/'
              -
                - !GetAtt cowinatorTable.Arn
                - 'index'
                - '*'

package:
  individually: true

functions:
  connect:
    handler: src/handlers/index.connect
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: src/handlers/index.disconnect
    events:
      - websocket:
          route: $disconnect

  message:
    handler: src/handlers/index.message
    events:
      - websocket:
          route: msg

custom:
  webpack:
    webpackConfig: './webpack.config.ts'
  dynamodb:
    start:
      migrate: true
      port: 8000
    stages:
      - dev

resources:
  Resources:
    cowinatorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cowinator_pool
        AttributeDefinitions:
          - AttributeName: "connection_id"
            AttributeType: "S"
          - AttributeName: "meeting_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "connection_id"
            KeyType: HASH
          - AttributeName: "meeting_id"
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: "meeting_index"
            KeySchema:
              - AttributeName: "meeting_id"
                KeyType: HASH
              - AttributeName: "connection_id"
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline


